tls:
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: true
      curvePreferences:
        - CurveP521
        - CurveP384
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
  certificates:
    - certFile: /etc/traefik/certs/homepage.embeddedsource.es.crt
      keyFile: /etc/traefik/certs/homepage.embeddedsource.es.key
    - certFile: /etc/traefik/certs/duplicati.embeddedsource.es.crt
      keyFile: /etc/traefik/certs/duplicati.embeddedsource.es.key
    - certFile: /etc/traefik/certs/auth.embeddedsource.es.crt
      keyFile: /etc/traefik/certs/auth.embeddedsource.es.key
    