# Use root/example as user/password credentials
version: '3.1'

services:

  # ordiso-backup-service:
  #   image: ubuntu
  #   tty: true
  #   container_name: ordiso-backup-service
  #   restart: unless-stopped
  #   environment:
  #     BACKUP_SERVICE: google-drive
  #   volumes:
  #     - ./backups/ordisodb:/backup/ordisodb:rw
  #     - ordisodb:/var/lib/mysql:rw

  ordiso-mysql:
    image: mysql
    container_name: ordiso-mysql
    restart: always
    # depends_on:
    #   - ordiso-backup-service
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: mypass
    # volumes_from:
    #   - ordiso-backup-service
    volumes:
      - ./tmp/backups/ordiso-mysql-data:/docker-entrypoint-initdb.d
    ports:
      - "33050:3306"

# volumes:
#   ordisodb:
#     name: ordisodb
#   ordisodb-backup:
#     name: ordisodb-backup

volumes:
  ordiso-mysql-data:
    name: ordiso-mysql-data
