version: '3.1'

services:

  nginx:
    image: nginx
    container_name: ordiso_nginx
    ports:
      - 2653:80
      - 33040:33040
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    depends_on:
      - data

  data:
    image: mysql:8.0
    container_name: ordiso_data
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ordiso
      MYSQL_USER: ordiso
      MYSQL_PASSWORD: ordiso
      MYSQL_ROOT_HOST: "%"
    ports:
      - "127.0.0.1:33050:3306"
    volumes:
      - ./tmp/backups/ordiso.db:/docker-entrypoint-initdb.d

  superset_db:
    # env_file:
    #   - path: docker/.env # default
    #     required: true
    #   - path: docker/.env-local # optional override
    #     required: false
    image: postgres:15
    container_name: superset_db
    restart: always
    environment:
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
    ports:
      - "127.0.0.1:54320:5432"
    volumes:
      - ./tmp/backups/ordiso.superset:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 7070:8080

  sphinx:
    image: ubuntu:latest
    container_name: sphinx-docs
    restart: always
    environment:
      DOCUMENTATION_ROOT_DIR: "/docs"
    ports:
        - 90:9000
    volumes:
        - ./docs:/docs
        - ./tools:/tools
    command: bash -c "cd /tools && ./docs-server.sh"
    

volumes:
  ordiso-mysql-data:
    name: ordiso-mysql-data
