version: '3'

services:
  nginx:
    image: nginx
    container_name: ordiso_nginx
    ports:
      - 2653:80
      - 33040:33040
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    depends_on:
      - data

  data:
    image: mysql:8.0
    container_name: ordiso_data
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ordiso
      MYSQL_USER: ordiso
      MYSQL_PASSWORD: ordiso
    ports:
      - "127.0.0.1:33050:3306"
