services:

  ordiso-traefik:
    image: traefik:v3.2
    container_name: ordiso-traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "33040:33040"
    volumes:
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./config/conf/:/etc/traefik/conf/
      - /data/volumes/ordiso-traefik-data/config/certs/:/etc/traefik/certs/
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - ordiso-traefik-default
    labels:
      traefik.enable: true
      traefik.http.routers.traefik_api.rule: Host(`traefik.embeddedsource.es`)
      traefik.http.routers.traefik_api.entrypoints: websecure
      traefik.http.routers.traefik_api.tls: true
      traefik.http.routers.traefik_api.tls.certResolver: production
      traefik.http.routers.traefik_api.service: api@internal
      traefik.http.routers.traefik_api.middlewares: basic-auth-global
      traefik.http.middlewares.basic-auth-global.basicauth.users: asanchez:$$2y$$05$$y28goziQZ0H6Zvs93SpF8eAQiD/hrexNpyLQ84JYIU.j0feMFFwRi, admin:$$2y$$05$$cFZJKWs8mPkQER/R034glukJlVQmg5ARpcdA8aptk07denfdEdBji

networks:
  ordiso-traefik-default:
    name: ordiso-traefik-default
    driver: bridge