---
services:
  ordiso-nextcloud:
    image: nextcloud:latest
    container_name: ordiso-nextcloud
    restart: unless-stopped
    env_file: .env
    volumes:
      - /data/volumes/ordiso-nextcloud-data/data:/var/www/html
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.enable: "true"
      traefik.http.routers.ordiso-nextcloud.rule: "Host(`nextcloud.embeddedsource.es`)"
      traefik.http.routers.ordiso-nextcloud.entrypoints: "web,websecure"
      traefik.http.routers.ordiso-nextcloud.tls: "true"
      traefik.http.routers.ordiso-nextcloud.tls.certresolver: "production"
    networks:
      - ordiso-traefik-default
      # - ordiso-nextcloud-internal
  
  ordiso-nextcloud-db:
    image: mariadb
    container_name: ordiso-nextcloud-db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /data/volumes/ordiso-nextcloud-db-data/data:/var/lib/mysql
    env_file: .env
    networks:
      - ordiso-traefik-default
      # - ordiso-nextcloud-internal

networks:
  ordiso-nextcloud-internal:
    name: ordiso-nextcloud-internal
    driver: bridge
  ordiso-traefik-default:
    external: true
  
