---
services:
  ordiso-telegram-bot:
    image: dgongut/docker-controller-bot:latest
    container_name: ordiso-telegram-bot
    restart: always
    env_file: .env
    volumes:
        - /data/volumes/ordiso-telegram-bot-data:/app/schedule
    tty: true
    networks:
      - ordiso-traefik-default
      - ordiso-telegram-bot-internal
  
networks:
  ordiso-traefik-default:
    external: true
  ordiso-telegram-bot-internal:
    name: ordiso-telegram-bot-internal
    driver: bridge