---
services:
  ordiso-homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: ordiso-homepage
    restart: unless-stopped
    ports:
      - 1500:3000
    volumes:
      - /data/volumes/ordiso-homepage-data/app/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.enable: "true"
      traefik.http.routers.ordiso-homepage.rule: "Host(`homepage.embeddedsource.es`)"
      traefik.http.routers.ordiso-homepage.entrypoints: "web,websecure"
      traefik.http.routers.ordiso-homepage.tls: "true"
      traefik.http.routers.ordiso-homepage.tls.certresolver: "production"
      traefik.http.routers.ordiso-homepage.middlewares: "authelia@docker"
    networks:
      - ordiso-traefik-default

  ordiso-dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: ordiso-dockerproxy
    environment:
      - CONTAINERS=1 # Allow access to viewing containers
      - SERVICES=1 # Allow access to viewing services (necessary when using Docker Swarm)
      - TASKS=1 # Allow access to viewing tasks (necessary when using Docker Swarm)
      - POST=0 # Disallow any POST operations (effectively read-only)
    ports:
      - 2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - ordiso-traefik-default

networks:
  ordiso-traefik-default:
    external: true