services:
  ordiso-adminer:
    image: adminer:latest
    restart: always
    container_name: ordiso-adminer
    labels:
      traefik.enable: "true"
      traefik.http.routers.ordiso-adminer.rule: "Host(`adminer.embeddedsource.es`)"
      traefik.http.routers.ordiso-adminer.entrypoints: "websecure"
      traefik.http.routers.ordiso-adminer.tls: "true"
      traefik.http.routers.ordiso-adminer.tls.certresolver: "production"
      traefik.http.services.ordiso-adminer.loadbalancer.server.port: "8080"
    networks:
      - ordiso-traefik-default

networks:
  ordiso-traefik-default:
    external: true