global:
  checkNewVersion: true
  sendAnonymousUsage: false

accessLog: {}

log:
  level: ERROR

api:
  dashboard: true
  insecure: false
  debug: false

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
    # forwardedHeaders:
    #   insecure: false
      # trustedIPs: []
    # proxyProtocol:
    #   insecure: false
      # trustedIPs: []
  websecure:
    address: :443
    # forwardedHeaders:
    #   insecure: false
      # trustedIPs: []
    # proxyProtocol:
    #   insecure: false
      # trustedIPs: []
  postgres:
    address: :54320
  mysql:
    address: :33050

certificatesResolvers:
  production:
    acme:
      email: andres.sanchez.engineering@gmail.com
      storage: /etc/traefik/certs/production-acme.json
      caServer: 'https://acme-v02.api.letsencrypt.org/directory'
      keyType: EC256
      httpChallenge:
        entryPoint: web

serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    exposedByDefault: false
    endpoint: 'unix:///var/run/docker.sock'
    watch: true
  file:
    directory: /etc/traefik/conf/
    watch: true